apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tmc-datadog
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: datadog
      sourceRef:
        kind: HelmRepository
        name: datadog
        namespace: default
      interval: 1m
  values:
    datadog:
      apiKey:  59400b67726d7debc83ee6fe8d9504af
      site:  datadoghq.eu
      apm:
        instrumentation:
          enabled: true
      kubelet:
        tlsVerify:  false
    providers:
      aks:
        enabled: true
    agents:
      enabled: true
      image:
        name: agent
        tag: 7.39.2

